default:
  image: docker:24.0.5-cli
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info

stages:
  - build

build:
  variables:
    # STORAGE_DRIVER: vfs
    # BUILDA_FORMAT: docker
    FQ_IMAGE_NAME: "$CI_REGISTRY_IMAGE"
    VERSION: "0.0.2"
    DOCKER_HOST: tcp://localhost:2376
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  # image: quay.io/buildah/stable
  stage: build
  before_script:
    # - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build -t $FQ_IMAGE_NAME:$VERSION .
    - docker push $FQ_IMAGE_NAME:$VERSION
    # - buildah images
    # - buildah build -t $FQ_IMAGE_NAME:$VERSION
    # - buildah tag $FQ_IMAGE_NAME:$VERSION $FQ_IMAGE_NAME:latest
    # - buildah images
    # - buildah push $FQ_IMAGE_NAME:$VERSION
    # - buildah push $FQ_IMAGE_NAME:latest
